apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume1810
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1810
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: collegefest
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage1810
              mountPath: /var/lib/mysql1810
      volumes:
        - name: mysql-persistent-storage1810
          persistentVolumeClaim:
            claimName: mysql-pv-claim1810
---
apiVersion: v1
kind: Service
metadata:
  name: mysql2
spec:
  ports:
    - port: 3306
  selector:
    app: mysql